# Generated by Django 3.2.13 on 2023-10-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akashicrecords', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='image',
            new_name='poster',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='date',
            new_name='release_date',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='description',
        ),
        migrations.AddField(
            model_name='movie',
            name='age_rating',
            field=models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG_13', 'PG_13'), ('R', 'R'), ('NC_17', 'NC_17')], default='G', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='box_office',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='main_cast',
            field=models.CharField(default='null', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='plot',
            field=models.CharField(default='null', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
