# Generated by Django 3.2.13 on 2023-10-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akashicrecords', '0002_auto_20231024_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.CharField(default=3, max_length=300),
            preserve_default=False,
        ),
    ]
