# Generated by Django 3.2.13 on 2023-11-14 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akashicrecords', '0007_alter_movie_age_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='likes',
        ),
    ]
