# Generated by Django 3.2.13 on 2023-11-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akashicrecords', '0009_auto_20231114_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='watched_movies',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
