# Generated by Django 3.2.13 on 2023-11-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akashicrecords', '0011_auto_20231114_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='watched_movies',
            field=models.ManyToManyField(to='akashicrecords.Movie'),
        ),
    ]
