# Generated by Django 3.2.13 on 2023-11-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akashicrecords', '0013_alter_movie_dvd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='dvd',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
