# Generated by Django 3.2.13 on 2023-11-20 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akashicrecords', '0014_alter_movie_dvd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='dvd',
        ),
    ]
