# Generated by Django 3.2.13 on 2023-11-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akashicrecords', '0015_remove_movie_dvd'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='dvd',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='total_seasons',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='box_office',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
