# Generated by Django 3.2.13 on 2023-11-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akashicrecords', '0016_auto_20231120_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='production',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='website',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='box_office',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_votes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='metascore',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(),
        ),
    ]
