# Generated by Django 3.2.13 on 2023-11-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akashicrecords', '0019_auto_20231120_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='end_year',
            field=models.IntegerField(null=True),
        ),
    ]
