# Generated by Django 3.2.13 on 2023-11-21 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akashicrecords', '0021_auto_20231121_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='movie',
        ),
    ]
