# Generated by Django 3.2.13 on 2023-11-21 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('akashicrecords', '0023_auto_20231121_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watched',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='watched',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='watched',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='watched',
            name='rating',
            field=models.FloatField(choices=[(0, '0'), (0.5, '0.5'), (1, '1'), (1.5, '1.5'), (2, '2'), (2.5, '2.5'), (3, '3'), (3.5, '3.5'), (4, '4'), (4.5, '4.5'), (5, '5')]),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akashicrecords.movie')),
                ('user_comment', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
