# Generated by Django 3.2.13 on 2023-12-03 04:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('akashicrecords', '0030_auto_20231203_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='profile',
            field=models.ManyToManyField(blank=True, to='akashicrecords.Profile'),
        ),
        migrations.AlterField(
            model_name='watched',
            name='movie',
            field=models.ManyToManyField(blank=True, to='akashicrecords.Movie'),
        ),
        migrations.AlterField(
            model_name='watched',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
