# Generated by Django 3.2.13 on 2023-12-03 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akashicrecords', '0035_alter_watched_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watched',
            name='movie',
        ),
        migrations.AddField(
            model_name='watched',
            name='movie',
            field=models.ForeignKey(default=76759, on_delete=django.db.models.deletion.CASCADE, to='akashicrecords.movie'),
        ),
    ]
